/*
    Auto-generated by: https://github.com/pmndrs/gltfjsx
    Command: npx gltfjsx@6.5.0 react.glb -T
    Author: xenadus (https://sketchfab.com/xenadus)
    License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
    Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
*/

import { Float, useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { useRef } from 'react';

const ReactLogo = (props) => {
  const { nodes, materials } = useGLTF('/models/react.glb');
  const logoRef = useRef();

  // Pulse effect using useFrame hook
  useFrame((state, delta) => {
    const time = state.clock.getElapsedTime();
    const scale = 0.3 + Math.sin(time * 3) * 0.05; // Pulse between 0.25 and 0.35
    logoRef.current.scale.set(scale, scale, scale);
  });

  return (
    <Float floatIntensity={3} speed={1.5} position={[7, 0, 0]}> {/* Adjusted position to move to the right */}
      <group ref={logoRef} scale={0.3} {...props} dispose={null}>
        <mesh
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 0.079, 0.181]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={[0.392, 0.392, 0.527]}
        />
      </group>
    </Float>
  );
};

useGLTF.preload('/models/react.glb');

export default ReactLogo;